version: 2

sphinx:
  configuration: docs/conf.py

formats: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/environment-doc.yaml

submodules:
  include: all
