name: model-diagnostics-doc
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - apscheduler
  - matplotlib
  - python>=3.9
  - panel
  - intake
  - access-nri-intake==0.0.9
  - ipython
  - numpy
  - sphinx
  - sphinx-autobuild
  - pip
  - pip:
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
    - -e ..
