name: model-diagnostics-doc
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python>=3.10
  - access-nri-intake
  - ipython
  - numpy
  - sphinx
  - sphinx-autobuild
  - pip
  - pip:
    - intake
    - intake-esm
    - ecgtools
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
