name: model-diagnostics-doc
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python>=3.10
  - access-nri-intake
  - apscheduler
  - panel
  - matplotlib
  - ipython
  - sphinx
  - sphinx-autobuild
  - sphinx-panels
  - pip
  - pip:
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
