name: model-diagnostics-doc
channels:
  - conda-forge
  - accessnri
  - defaults
  - free
dependencies:
  - python>=3.10
  - intake
  - intake-esm
  - ecgtools
  - access-nri-intake
  - ipython
  - numpy
  - sphinx
  - sphinx-autobuild
  - pip
  - pip:
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
