name: model-diagnostics-doc
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python>=3.9
  - intake
  - ipython
  - numpy
  - sphinx
  - sphinx-autobuild
  - pip
  - pip:
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
