name: model-diagnostics-doc
channels:
  - conda-forge
  - accessnri
  - defaults
  - free
dependencies:
  - python>=3.10
  - intake>=0.7.0
  - intake-esm>=2023.7.7
  - ecgtools>=2023.7.13
  - access-nri-intake
  - ipython
  - numpy
  - sphinx
  - sphinx-autobuild
  - pip
  - pip:
    - sphinx-autoapi
    - sphinx-rtd-theme
    - sphinxcontrib-napoleon
